export const SUBJECTS = [
  "ادبیات Literature",
  "اقتصاد Economy",
  "انسانشناسی Anthropology",
  "تاریخ History",
  "جامعهشناسی Sociology",
  "جغرافیا Geography",
  "حقوق Law",
  "خدمات اجتماعی Social Services",
  "روابط بینالملل International Relations",
  "روانشناسی Psychology",
  "زبانشناسی Linguistics",
  "سایر هنرها Other Arts",
  "علوم تربیتی Education",
  "علوم سیاسی Political Science",
  "فلسفه Philosophy",
  "مطالعات جنسیت Gender Studies",
  "مطالعات دینی Religious Studies",
  "مطالعات فرهنگی Cultural Studies",
  "مطالعات رسانه Media Studies",
  "مطالعات علم و فناوری Science and Technology Studies",
  "مطالعات فیلم Film Studies",
  "مطالعات محیط زیست Environmental Studies",
  "معماری Architecture",
  "مدیریت Management",
  "موسیقی Music",
  "بهداشت عمومی Public Health"
];
